[program:haproxy]
command=haproxy -f /etc/haproxy/haproxy.cfg -db
priority=20
autostart=true
autorestart=true
startretries=3
startsecs=3
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
redirect_stderr=true
user=root
